### ISSUE TITLE
Recursion if installed manually and updated with Git

### ISSUE THREAD

**Issue by ain** [tmux-plugins/tmux-test#1]
Are you aware that a recursion here will cause trouble when updating tmux submodules?

E.g.: `git submodule update --recursive --init` will result in:

```
Submodule path 'plugins/tmux-resurrect': checked out '6a6a87626af5d4b9e2553093f5c270a4ccf7707f'
Submodule path 'plugins/tmux-resurrect/lib/tmux-test': checked out '1778f06b20279247ca153314bf9cfffee109e9c7'
Submodule path 'plugins/tmux-resurrect/lib/tmux-test/lib/tmux-test': checked out '6d423b6b743090e5831b55168eb2ddafc37c4f1c'
Submodule path 'plugins/tmux-resurrect/lib/tmux-test/lib/tmux-test/lib/tmux-test': checked out '1b1563d7d7f72d36aee861f87845d714a651c0a5'
Submodule path 'plugins/tmux-resurrect/lib/tmux-test/lib/tmux-test/lib/tmux-test/lib/tmux-test': checked out 'cf493c83fc9bc19b4eab955725555448296418fc'
Submodule path 'plugins/tmux-resurrect/lib/tmux-test/lib/tmux-test/lib/tmux-test/lib/tmux-test/lib/tmux-test': checked out '671dc6062182a1979183cfed34ed27914c47941a'
Submodule path 'plugins/tmux-resurrect/lib/tmux-test/lib/tmux-test/lib/tmux-test/lib/tmux-test/lib/tmux-test/lib/tmux-test': checked out '23a614576eb48affeaa82e4334f6d8d26f46461c'
```

**Comment by bentruyman** [comment]
Can confirm this issue. I have [tmux-resurrect](https://github.com/tmux-plugins/tmux-resurrect) as a submodule in my [dotfiles](https://github.com/bentruyman/dotfiles) and I recently began experiencing this issue.

**Comment by ain** [comment]
Yes, and the reason is actually quite simple: https://github.com/tmux-plugins/tmux-test/blob/master/.gitmodules#L1-L3

**Comment by bruno-** [comment]
Oh my, this is not nice.. thanks for reporting this guys.
The reason why we have `tmux-test` as a submodule within itself is so that `tmux-test` can test itself.

I'll start investigating.

**Comment by ain** [comment]
You could probably just commit it into the current repo then and give up on
the submodule. Or have another separate repo chiefly for testing purposes :)

**Comment by bruno-** [comment]
Hi guys,
I think this is now fixed. I've removed the submodule recursion from `tmux-test` repo.

Can you please try pulling newest `tmux-resurrect` plugin version and see if everything is ok?
Thanks

**Comment by ain** [comment]
Yup, all is fine now :+1:
